FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN set -e; \
    apt-get update && \
    apt-get -y install netcat-traditional gettext httpie && \
    pip install --upgrade pip && \
    pip install flask


RUN mkdir /code
WORKDIR /code
COPY ./server.py .

ENTRYPOINT ["python","./server.py"]